source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NickFoundation_Example' do
  pod 'NickFoundation', :path => '../'
end

target 'NickFoundation_Tests' do
  pod 'NickFoundation', :path => '../'  
end
