source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NickFoundation_Example' do
  pod 'NickFoundation', :path => '../'
  pod 'NickFoundation/CoreData', :path => '../'
  pod 'NickFoundation/Encode', :path => '../'
  pod 'NickFoundation/QRCode', :path => '../'

end

target 'NickFoudation-Example-OSX' do
    pod 'NickFoundation', :path => '../'
    pod 'NickFoundation/Encode', :path => '../'
end

target 'NickFoundation_Tests' do
  pod 'NickFoundation', :path => '../'  
end
