source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NickFoundation_Example', :exclusive => true do
  pod 'NickFoundation', :path => '../'
end

target 'NickFoundation_Tests', :exclusive => true do
  pod 'NickFoundation', :path => '../'

  
end
